version: '3'
services:
  data-engine-service:
    image: 23051999/tripy
    ports:
      - "8083:8083"
    links:
      - kafka
  zookeeper:
    image: zookeeper:3.7.0
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    links:
      - zookeeper
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "GeoNodes:1:1,rawPlaces:1:1"
